services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pandemic_visualization_api
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=pandemic_user
      - MYSQL_PASSWORD=pandemic_password
      - MYSQL_DATABASE=pandemic_db
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - pandemic-network

  db:
    image: mysql:8.0
    container_name: pandemic_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=pandemic_db
      - MYSQL_USER=pandemic_user
      - MYSQL_PASSWORD=pandemic_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - pandemic-network
    restart: unless-stopped

networks:
  pandemic-network:
    driver: bridge

volumes:
  mysql_data: